services:
  mysqldb:
    image: mysql:8.0.40
    ports:
      - '3306:3306'

    volumes:
      - ./data:/var/lib/mysql
     # - ./schema:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=DB
      - MYSQL_USER=name
      - MYSQL_PASSWORD=pass